/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FramePendataan extends javax.swing.JFrame {

    /**
     * Creates new form FramePendataan
     */
    public FramePendataan() {
        initComponents();
        LoadData();
        setTitle("ZAKAT PRO 3.0");

    }

    private void kosongkan_form() {
        teks_KTP.setEditable(true);
        teks_KTP.setText(null);
        teks_Nama.setText(null);
        cb_jenisKelamin.setSelectedItem(this);
        teks_Alamat.setText(null);
        teks_Nisab.setText(null);
        teks_Penghasilan.setText(null);
        teks_Total.setText(null);
        teks_Emas.setText(null);
    }

    void LoadData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.KTP");
        model.addColumn("Nama");
        model.addColumn("Jenis_Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Penghasilan");
        model.addColumn("Harga_Emas/1Gr");
        model.addColumn("Nisab");
        model.addColumn("Total_Zakat");
        try {
            String sql = "SELECT * FROM tbl_zakat";
            Connection conn = Koneksi.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] row = new Object[8];
                row[0] = rs.getString("KTP");
                row[1] = rs.getString("Nama");
                row[2] = rs.getString("Jenis_Kelamin");
                row[3] = rs.getString("Alamat");
                row[4] = rs.getString("Penghasilan");
                row[5] = rs.getString("Harga_Emas");
                row[6] = rs.getString("Nisab");
                row[7] = rs.getString("Total_Zakat");
                model.addRow(row);
            }
            tblZakat.setModel(model);

        } catch (SQLException e) {
            System.out.println("Koneksi gagal " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        list1 = new java.awt.List();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Btn_Kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teks_KTP = new javax.swing.JTextField();
        teks_Nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teks_Alamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZakat = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        teks_Penghasilan = new javax.swing.JTextField();
        teks_Total = new javax.swing.JTextField();
        teks_Emas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        teks_Nisab = new javax.swing.JTextField();
        btn_Simpan = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Proses = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_Clear = new javax.swing.JButton();
        cb_jenisKelamin = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(23, 101, 56));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Baznas kecil.png"))); // NOI18N
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 19, -1, 105));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/k.png"))); // NOI18N
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 138, -1));

        Btn_Kembali.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Kembali.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        Btn_Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_undo_30px.png"))); // NOI18N
        Btn_Kembali.setText("KEMBALI");
        Btn_Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_KembaliMouseClicked(evt);
            }
        });
        panel.add(Btn_Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, 150, 47));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel4.setText("No.KTP");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel5.setText("NAMA");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        teks_KTP.setBackground(new java.awt.Color(255, 255, 204));
        teks_KTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teks_KTPKeyPressed(evt);
            }
        });
        panel.add(teks_KTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 232, -1));

        teks_Nama.setBackground(new java.awt.Color(255, 255, 204));
        panel.add(teks_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 232, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel6.setText("JENIS KELAMIN");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel7.setText("ALAMAT");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        teks_Alamat.setBackground(new java.awt.Color(255, 255, 204));
        panel.add(teks_Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 330, -1));

        tblZakat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.KTP", "Nama", "Jenis Kelamin", "Alamat", "Penghasilan", "Harga Emas/1Gr", "Nisab", "Total Zakat"
            }
        ));
        tblZakat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblZakatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblZakat);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 1070, 155));

        jPanel1.setBackground(new java.awt.Color(187, 223, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel1.setText("PENDATAAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1120, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel9.setText("PENGHASILAN");
        panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, 20));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel10.setText("HARGA EMAS / 1Gr");
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel11.setText("NISAB (85Gr Emas)");
        panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 120, -1));

        teks_Penghasilan.setBackground(new java.awt.Color(255, 255, 204));
        teks_Penghasilan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teks_PenghasilanKeyPressed(evt);
            }
        });
        panel.add(teks_Penghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 270, -1));

        teks_Total.setEditable(false);
        teks_Total.setBackground(new java.awt.Color(255, 255, 204));
        panel.add(teks_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 270, -1));

        teks_Emas.setBackground(new java.awt.Color(255, 255, 204));
        teks_Emas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teks_EmasKeyPressed(evt);
            }
        });
        panel.add(teks_Emas, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 270, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jLabel12.setText("TOTAL ZAKAT");
        panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        teks_Nisab.setEditable(false);
        teks_Nisab.setBackground(new java.awt.Color(255, 255, 204));
        panel.add(teks_Nisab, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 270, -1));

        btn_Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_save_20px.png"))); // NOI18N
        btn_Simpan.setText("SIMPAN");
        btn_Simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SimpanMouseClicked(evt);
            }
        });
        panel.add(btn_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_pencil_drawing_20px.png"))); // NOI18N
        btn_Edit.setText("EDIT");
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditMouseClicked(evt);
            }
        });
        panel.add(btn_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 90, 30));

        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_trash_can_20px.png"))); // NOI18N
        btn_Delete.setText("DELETE");
        btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseClicked(evt);
            }
        });
        panel.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        btn_Proses.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        btn_Proses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_rotate_20px.png"))); // NOI18N
        btn_Proses.setText("PROSES");
        btn_Proses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ProsesMouseClicked(evt);
            }
        });
        panel.add(btn_Proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, -1, -1));

        jPanel2.setBackground(new java.awt.Color(187, 223, 254));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel8.setText("HITUNG ZAKAT PROFESI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 230, 30));

        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_broom_20px.png"))); // NOI18N
        btn_Clear.setText("CLEAR");
        btn_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ClearMouseClicked(evt);
            }
        });
        panel.add(btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        cb_jenisKelamin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        cb_jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki - Laki", "Perempuan" }));
        cb_jenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jenisKelaminActionPerformed(evt);
            }
        });
        panel.add(cb_jenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 120, -1));

        jPanel3.setBackground(new java.awt.Color(187, 223, 254));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel14.setText("BIODATA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 120, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/green-blue-combination-inside-wallpaper-preview222.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 800));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1128, 798));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_KembaliMouseClicked
        // TODO add your handling code here:
        FrameMenu menu = new FrameMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Btn_KembaliMouseClicked

    private void btn_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ClearMouseClicked
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_btn_ClearMouseClicked

    private void btn_SimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SimpanMouseClicked
        // TODO add your handling code here:
        int ktp = Integer.parseInt(teks_KTP.getText());
        String nama = teks_Nama.getText();
        String alamat = teks_Alamat.getText();
        int penghasilan = Integer.parseInt(teks_Penghasilan.getText());
        int hargaEmas = Integer.parseInt(teks_Emas.getText());
        String nisabstr = teks_Nisab.getText();
        String totalstr = teks_Nisab.getText();
        if (nisabstr.equals("") || totalstr.equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan Masukkan Data dan Proses");

        } else {
            int totalZakat = 0;
            int nisab = Integer.parseInt(nisabstr);
            totalZakat = Integer.parseInt(teks_Total.getText());
            try {
                String sql = "INSERT INTO tbl_zakat VALUES('" + ktp + "', '" + nama
                        + "', '" + cb_jenisKelamin.getSelectedItem() + "', '" + alamat + "', '" + penghasilan + "', '" + hargaEmas
                        + "', '" + nisab + "', '" + totalZakat
                        + "')";
                java.sql.Connection conn = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement ptsm = conn.prepareStatement(sql);
                ptsm.execute(sql);
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
                LoadData();
                kosongkan_form();

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_SimpanMouseClicked

    private void cb_jenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_jenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_jenisKelaminActionPerformed

    private void btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM tbl_zakat WHERE KTP ='" + teks_KTP.getText() + "'";
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement ptsm = conn.prepareStatement(sql);
            ptsm.execute(sql);
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            LoadData();
            kosongkan_form();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_DeleteMouseClicked

    private void tblZakatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblZakatMouseClicked
        // TODO add your handling code here:
        int baris = tblZakat.rowAtPoint(evt.getPoint());
        String ktp = tblZakat.getValueAt(baris, 0).toString();
        teks_KTP.setText(ktp);
        String nama = tblZakat.getValueAt(baris, 1).toString();
        teks_Nama.setText(nama);
        String jenisKelamin = tblZakat.getValueAt(baris, 2).toString();
        cb_jenisKelamin.setSelectedItem(jenisKelamin);
        String alamat = tblZakat.getValueAt(baris, 3).toString();
        teks_Alamat.setText(alamat);
        String penghasilan = tblZakat.getValueAt(baris, 4).toString();
        teks_Penghasilan.setText(penghasilan);
        String hargaEmas = tblZakat.getValueAt(baris, 5).toString();
        teks_Emas.setText(hargaEmas);
        String nisab = tblZakat.getValueAt(baris, 6).toString();
        teks_Nisab.setText(nisab);
        String total = tblZakat.getValueAt(baris, 7).toString();
        teks_Total.setText(total);
    }//GEN-LAST:event_tblZakatMouseClicked

    private void btn_ProsesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ProsesMouseClicked
        // TODO add your handling code here:
        int penghasilan = Integer.parseInt(teks_Penghasilan.getText());
        int hargaEmas = Integer.parseInt(teks_Emas.getText());
        long nisab = 85 * hargaEmas;
        teks_Nisab.setText(nisab + "");
        if (penghasilan >= nisab) {
            double totalZakat = 2.5/100 * penghasilan;
            int total = (int)totalZakat;
            teks_Total.setText(total + "");
        } else {
            JOptionPane.showMessageDialog(null, "Nisab Belum Terpenuhi");
            teks_Total.setText(0 + "");
        }
    }//GEN-LAST:event_btn_ProsesMouseClicked

    private void btn_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseClicked
        // TODO add your handling code here:
        Object jenisKelamin = cb_jenisKelamin.getSelectedItem();
        try {
            String sql = "update  tbl_zakat SET KTP ='" + teks_KTP.getText() + "', Nama ='" + teks_Nama.getText()
                    + "',Jenis_Kelamin =' " + jenisKelamin + "', Alamat = '" + teks_Alamat.getText()
                    + "',Penghasilan= '" + teks_Penghasilan.getText() + "', Harga_Emas='" + teks_Emas.getText()
                    + "', Nisab = '" + teks_Nisab.getText() + "', Total_Zakat = '" + teks_Total.getText() + "'"
                    + "WHERE KTP ='" + teks_KTP.getText() + "' OR nama='" + teks_Nama.getText() + "'";;

            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement ptsm = conn.prepareStatement(sql);
            ptsm.execute(sql);
            JOptionPane.showMessageDialog(this, "Data Berhasil Di update");
            LoadData();
            kosongkan_form();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_EditMouseClicked

    private void teks_KTPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_KTPKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
            evt.consume();

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "Hanya Boleh Diinputkan Angka");

        }
    }//GEN-LAST:event_teks_KTPKeyPressed

    private void teks_PenghasilanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_PenghasilanKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
            evt.consume();

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "Hanya Boleh Diinputkan Angka");

        }
    }//GEN-LAST:event_teks_PenghasilanKeyPressed

    private void teks_EmasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_EmasKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
            evt.consume();

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "Hanya Boleh Diinputkan Angka");

        }
    }//GEN-LAST:event_teks_EmasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePendataan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Kembali;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Proses;
    private javax.swing.JButton btn_Simpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_jenisKelamin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.List list1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblZakat;
    private javax.swing.JTextField teks_Alamat;
    private javax.swing.JTextField teks_Emas;
    private javax.swing.JTextField teks_KTP;
    private javax.swing.JTextField teks_Nama;
    private javax.swing.JTextField teks_Nisab;
    private javax.swing.JTextField teks_Penghasilan;
    private javax.swing.JTextField teks_Total;
    // End of variables declaration//GEN-END:variables
}
