/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrameLihatData extends javax.swing.JFrame {

    /**
     * Creates new form FrameLihatData
     */
    public FrameLihatData() {
        initComponents();
        LoadData();
        setTitle("ZAKAT PRO 3.0");

    }

    private void kosongkan_form() {
        teks_KTP.setEditable(true);
        teks_KTP.setText(null);
        teks_Nama.setText(null);
    }

    void CariData(String key) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.KTP");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Penghasilan");
        model.addColumn("Harga Emas/1Gr");
        model.addColumn("Nisab");
        model.addColumn("Total Zakat");
        try {
            Connection conn = Koneksi.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * from tbl_zakat WHERE Nama LIKE '%" + key + "%' OR KTP LIKE '%" + key + "%'");

            while (rs.next()) {
                Object[] row = new Object[8];
                row[0] = rs.getString("KTP");
                row[1] = rs.getString("Nama");
                row[2] = rs.getString("Jenis_Kelamin");
                row[3] = rs.getString("Alamat");
                row[4] = rs.getString("Penghasilan");
                row[5] = rs.getString("Harga_Emas");
                row[6] = rs.getString("Nisab");
                row[7] = rs.getString("Total_Zakat");

                model.addRow(row);
            }
            tblZakat.setModel(model);
        } catch (SQLException e) {
            System.out.println("Koneksi gagal " + e.toString());
        }
    }

    void LoadData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.KTP");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Penghasilan");
        model.addColumn("Harga Emas/1Gr");
        model.addColumn("Nisab");
        model.addColumn("Total Zakat");
        try {
            String sql = "SELECT * FROM tbl_zakat";
            Connection conn = Koneksi.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] row = new Object[8];
                row[0] = rs.getString("KTP");
                row[1] = rs.getString("Nama");
                row[2] = rs.getString("Jenis_Kelamin");
                row[3] = rs.getString("Alamat");
                row[4] = rs.getString("Penghasilan");
                row[5] = rs.getString("Harga_Emas");
                row[6] = rs.getString("Nisab");
                row[7] = rs.getString("Total_Zakat");

                model.addRow(row);
            }
            tblZakat.setModel(model);

        } catch (SQLException e) {
            System.out.println("Koneksi gagal " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZakat = new javax.swing.JTable();
        Btn_Kembali = new javax.swing.JButton();
        teks_KTP = new javax.swing.JTextField();
        teks_Nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Hapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teks_Cari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(23, 101, 56));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Baznas kecil.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/k.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 13, 138, 113));

        tblZakat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.KTP", "Nama", "Jenis Kelamin", "Alamat", "Penghasilan", "Harga Emas", "Nisab", "Total Zakat"
            }
        ));
        tblZakat.setRowHeight(25);
        tblZakat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblZakatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblZakat);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 825, 350));

        Btn_Kembali.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Kembali.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        Btn_Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_undo_30px.png"))); // NOI18N
        Btn_Kembali.setText("KEMBALI");
        Btn_Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_KembaliMouseClicked(evt);
            }
        });
        Btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KembaliActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 130, -1));

        teks_KTP.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.add(teks_KTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 229, 137, -1));

        teks_Nama.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.add(teks_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 229, 150, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel5.setText("No.KTP");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 202, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel6.setText("Nama");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 202, -1, -1));

        btn_Hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_Hapus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        btn_Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_trash_can_20px.png"))); // NOI18N
        btn_Hapus.setText("HAPUS");
        btn_Hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HapusMouseClicked(evt);
            }
        });
        jPanel3.add(btn_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 100, -1));

        jPanel1.setBackground(new java.awt.Color(187, 223, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel1.setText("DATA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 0, 130, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 923, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jLabel7.setText("Cari");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 50, -1));

        teks_Cari.setBackground(new java.awt.Color(255, 255, 204));
        teks_Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_CariKeyReleased(evt);
            }
        });
        jPanel3.add(teks_Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/green-blue-combination-inside-wallpaper-preview222.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(923, 701));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_KembaliMouseClicked
        // TODO add your handling code here:
        FrameMenu menu = new FrameMenu();

        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Btn_KembaliMouseClicked

    private void btn_HapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HapusMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM tbl_zakat WHERE KTP ='" + teks_KTP.getText() + "'";
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement ptsm = conn.prepareStatement(sql);
            ptsm.execute(sql);
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            LoadData();
            kosongkan_form();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_HapusMouseClicked

    private void tblZakatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblZakatMouseClicked
        // TODO add your handling code here:
        int baris = tblZakat.rowAtPoint(evt.getPoint());
        String ktp = tblZakat.getValueAt(baris, 0).toString();
        teks_KTP.setText(ktp);
        String nama = tblZakat.getValueAt(baris, 1).toString();
        teks_Nama.setText(nama);
    }//GEN-LAST:event_tblZakatMouseClicked

    private void Btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_KembaliActionPerformed

    private void teks_CariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_CariKeyReleased
        // TODO add your handling code here:
        String key = teks_Cari.getText();

        if (key != "") {
            CariData(key);
        } else {
            LoadData();
        }
    }//GEN-LAST:event_teks_CariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLihatData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLihatData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLihatData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLihatData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLihatData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Kembali;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZakat;
    private javax.swing.JTextField teks_Cari;
    private javax.swing.JTextField teks_KTP;
    private javax.swing.JTextField teks_Nama;
    // End of variables declaration//GEN-END:variables
}
